AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-py-suburi

  Powertools example

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: python3.12

    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  userFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      CodeUri: api/user
      Description: user function
      Architectures:
      - x86_64
      Tracing: Active
      Events:
        HelloPath:
          Type: Api
          Properties:
            Path: /user/{userid}
            Method: POST
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: userapi
          POWERTOOLS_METRICS_NAMESPACE: Powertools
          LOG_LEVEL: INFO
      Tags:
        LambdaPowertools: python
# Outputs:
#   HelloWorldApi:
#     Description: API Gateway endpoint URL for Prod environment for Hello World Function
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"
#   HelloWorldFunction:
#     Description: Hello World Lambda Function ARN
#     Value: !GetAtt HelloWorldFunction.Arn

